### ISSUE TITLE
Update Homebrew Cask URL

### ISSUE THREAD

**Issue by reitermarkus** [mikemcbride/website#4]
Hi, we just wanted to let you know that you are still linking to the old Homebrew Cask homepage (`caskroom.io`) in [`Uses.vue`](https://github.com/mikemcbride/website/blob/4ada40c85d7f2101a016d52e94cccb6211600155/src/pages/Uses.vue). This domain expired a few years ago and is not controlled by Homebrew anymore.

When you get a chance, please update the link to https://brew.sh/ or https://formulae.brew.sh/cask/.

Thank you,
the Homebrew team.

**Comment by mikemcbride** [comment]
Thanks!!
